import {
  Enterprise,
  Branch,
  Role,
  User,
  Product,
  Customer,
  Supplier,
  SubscriptionPlan,
  RestaurantTable,
  KitchenOrder,
  MedicineBatch,
  RepairTicket,
  HotelRoom,
  Sale,
  StockTransfer,
  AuditLog
} from '../types';

export const INITIAL_ROLES: Role[] = [
  {
    id: 'role-super-admin',
    title: 'Super Admin',
    description: 'Full platform administration & enterprise control',
    permissions: [
      'sales.view', 'sales.create', 'sales.edit', 'sales.delete', 'sales.refund',
      'products.view', 'products.create', 'products.edit', 'products.delete',
      'inventory.view', 'inventory.create', 'inventory.adjust', 'inventory.transfer',
      'purchases.view', 'purchases.create', 'purchases.edit',
      'customers.view', 'customers.create', 'customers.edit',
      'suppliers.view', 'suppliers.create', 'suppliers.edit',
      'reports.view', 'reports.export',
      'barcode.generate', 'barcode.print', 'barcode.regenerate',
      'settings.view', 'settings.manage',
      'users.view', 'users.create', 'users.edit', 'users.delete'
    ],
    isSystem: true
  },
  {
    id: 'role-owner',
    title: 'Enterprise Owner',
    description: 'Enterprise executive with full business control across branches',
    permissions: [
      'sales.view', 'sales.create', 'sales.edit', 'sales.delete', 'sales.refund',
      'products.view', 'products.create', 'products.edit', 'products.delete',
      'inventory.view', 'inventory.create', 'inventory.adjust', 'inventory.transfer',
      'purchases.view', 'purchases.create', 'purchases.edit',
      'customers.view', 'customers.create', 'customers.edit',
      'suppliers.view', 'suppliers.create', 'suppliers.edit',
      'reports.view', 'reports.export',
      'barcode.generate', 'barcode.print', 'barcode.regenerate',
      'settings.view', 'settings.manage',
      'users.view', 'users.create', 'users.edit'
    ],
    isSystem: true
  },
  {
    id: 'role-branch-manager',
    title: 'Branch Manager',
    description: 'Branch supervisor managing daily sales, stock, and cashiers',
    permissions: [
      'sales.view', 'sales.create', 'sales.edit', 'sales.refund',
      'products.view',
      'inventory.view', 'inventory.adjust', 'inventory.transfer',
      'purchases.view', 'purchases.create',
      'customers.view', 'customers.create',
      'reports.view',
      'barcode.generate', 'barcode.print',
      'users.view'
    ],
    isSystem: true
  },
  {
    id: 'role-cashier',
    title: 'Cashier / POS Operator',
    description: 'Fast front-line sales cashier, receipt printer, and register operator',
    permissions: [
      'sales.view', 'sales.create', 'sales.refund',
      'products.view',
      'customers.view', 'customers.create',
      'barcode.print'
    ],
    isSystem: true
  }
];

export const INITIAL_SUBSCRIPTION_PLANS: SubscriptionPlan[] = [
  {
    id: 'plan-starter',
    name: 'Starter Retail',
    priceMonthly: 39,
    maxBranches: 1,
    maxUsers: 3,
    maxProducts: 1000,
    features: ['Core POS', 'Basic Inventory', 'Thermal Barcode Printing', 'Daily Sales Report'],
    description: 'Ideal for single retail shops, cafes, and independent boutiques.'
  },
  {
    id: 'plan-pro',
    name: 'Professional Business',
    priceMonthly: 89,
    maxBranches: 3,
    maxUsers: 10,
    maxProducts: 10000,
    features: ['Core POS', 'Advanced Inventory & Transfers', 'Industry Specialized Modules', 'Batch & Expiry', 'Supplier Management', 'CSV Import/Export'],
    description: 'Designed for expanding businesses, multi-branch stores, and restaurants.'
  },
  {
    id: 'plan-enterprise',
    name: 'SaaS Enterprise Unlimited',
    priceMonthly: 199,
    maxBranches: 25,
    maxUsers: 100,
    maxProducts: 100000,
    features: ['All Industry Modules Enabled', 'Unlimited Branches', 'Dedicated KDS & Housekeeping', 'Priority Cloud Sync', 'Full Audit Logging', 'Custom Roles & API'],
    description: 'Complete suite for restaurant chains, pharmacy networks, and hotel franchises.'
  }
];

export const INITIAL_ENTERPRISES: Enterprise[] = [
  {
    id: 'ent-hardware',
    name: 'ABC Hardware & Industrial Tools',
    slug: 'abc-hardware',
    code: 'ABC-HDW',
    category: 'hardware',
    phone: '+1 (555) 234-8900',
    email: 'contact@abchardware.com',
    address: '450 Industrial Parkway, Industrial Zone',
    currency: 'USD',
    taxRate: 8.5,
    vatNumber: 'US-8492048-A',
    status: 'active',
    subscriptionPlanId: 'plan-pro',
    modules: {
      corePos: true,
      inventory: true,
      purchasing: true,
      customers: true,
      suppliers: true,
      accounting: true,
      barcodeSystem: true,
      restaurant: false,
      pharmacy: false,
      hardwareStore: true,
      computerMobile: false,
      clothingShoe: false,
      hotel: false
    },
    features: {
      restaurantTables: false,
      restaurantKds: false,
      restaurantRecipes: false,
      restaurantSplitBills: false,
      restaurantTakeaway: false,
      pharmacyBatchTracking: false,
      pharmacyExpiryTracking: false,
      pharmacyPrescriptions: false,
      pharmacyFefo: false,
      hardwareUnitConversions: true,
      hardwareBulkWpricing: true,
      electronicsImeiTracking: false,
      electronicsSerialNumbers: false,
      electronicsRepairService: false,
      clothingVariantMatrix: false,
      hotelRooms: false,
      hotelReservations: false,
      hotelHousekeeping: false,
      hotelRoomBilling: false,
      cashRegisterShift: true,
      expenseTracking: true
    },
    createdAt: '2025-01-10T08:00:00Z',
    updatedAt: '2026-03-01T10:00:00Z'
  },
  {
    id: 'ent-restaurant',
    name: 'City Flavors Bistro & Lounge',
    slug: 'city-flavors',
    code: 'CTY-BST',
    category: 'restaurant',
    phone: '+1 (555) 456-7890',
    email: 'info@cityflavors.com',
    address: '88 Waterfront Promenade, Marina Bay',
    currency: 'USD',
    taxRate: 10.0,
    vatNumber: 'US-9214710-R',
    status: 'active',
    subscriptionPlanId: 'plan-pro',
    modules: {
      corePos: true,
      inventory: true,
      purchasing: true,
      customers: true,
      suppliers: true,
      accounting: true,
      barcodeSystem: true,
      restaurant: true,
      pharmacy: false,
      hardwareStore: false,
      computerMobile: false,
      clothingShoe: false,
      hotel: false
    },
    features: {
      restaurantTables: true,
      restaurantKds: true,
      restaurantRecipes: true,
      restaurantSplitBills: true,
      restaurantTakeaway: true,
      pharmacyBatchTracking: false,
      pharmacyExpiryTracking: false,
      pharmacyPrescriptions: false,
      pharmacyFefo: false,
      hardwareUnitConversions: false,
      hardwareBulkWpricing: false,
      electronicsImeiTracking: false,
      electronicsSerialNumbers: false,
      electronicsRepairService: false,
      clothingVariantMatrix: false,
      hotelRooms: false,
      hotelReservations: false,
      hotelHousekeeping: false,
      hotelRoomBilling: false,
      cashRegisterShift: true,
      expenseTracking: true
    },
    createdAt: '2025-02-15T09:30:00Z',
    updatedAt: '2026-03-01T11:00:00Z'
  },
  {
    id: 'ent-pharmacy',
    name: 'Apex Care Pharmacy & Wellness',
    slug: 'apex-care',
    code: 'APX-PHM',
    category: 'pharmacy',
    phone: '+1 (555) 789-0123',
    email: 'support@apexpharmacy.com',
    address: '12 Medical Center Blvd, Health City',
    currency: 'USD',
    taxRate: 5.0,
    vatNumber: 'US-4820194-P',
    status: 'active',
    subscriptionPlanId: 'plan-enterprise',
    modules: {
      corePos: true,
      inventory: true,
      purchasing: true,
      customers: true,
      suppliers: true,
      accounting: true,
      barcodeSystem: true,
      restaurant: false,
      pharmacy: true,
      hardwareStore: false,
      computerMobile: false,
      clothingShoe: false,
      hotel: false
    },
    features: {
      restaurantTables: false,
      restaurantKds: false,
      restaurantRecipes: false,
      restaurantSplitBills: false,
      restaurantTakeaway: false,
      pharmacyBatchTracking: true,
      pharmacyExpiryTracking: true,
      pharmacyPrescriptions: true,
      pharmacyFefo: true,
      hardwareUnitConversions: false,
      hardwareBulkWpricing: false,
      electronicsImeiTracking: false,
      electronicsSerialNumbers: false,
      electronicsRepairService: false,
      clothingVariantMatrix: false,
      hotelRooms: false,
      hotelReservations: false,
      hotelHousekeeping: false,
      hotelRoomBilling: false,
      cashRegisterShift: true,
      expenseTracking: true
    },
    createdAt: '2025-03-01T07:45:00Z',
    updatedAt: '2026-03-02T14:10:00Z'
  },
  {
    id: 'ent-hotel',
    name: 'Grand Horizon Luxury Hotel & Resort',
    slug: 'grand-horizon',
    code: 'GHD-HTL',
    category: 'hotel',
    phone: '+1 (555) 901-2345',
    email: 'frontdesk@grandhorizon.com',
    address: '777 Oceanview Way, Coastal Haven',
    currency: 'USD',
    taxRate: 12.0,
    vatNumber: 'US-7719230-H',
    status: 'active',
    subscriptionPlanId: 'plan-enterprise',
    modules: {
      corePos: true,
      inventory: true,
      purchasing: true,
      customers: true,
      suppliers: true,
      accounting: true,
      barcodeSystem: true,
      restaurant: true,
      pharmacy: false,
      hardwareStore: false,
      computerMobile: false,
      clothingShoe: false,
      hotel: true
    },
    features: {
      restaurantTables: true,
      restaurantKds: true,
      restaurantRecipes: false,
      restaurantSplitBills: true,
      restaurantTakeaway: true,
      pharmacyBatchTracking: false,
      pharmacyExpiryTracking: false,
      pharmacyPrescriptions: false,
      pharmacyFefo: false,
      hardwareUnitConversions: false,
      hardwareBulkWpricing: false,
      electronicsImeiTracking: false,
      electronicsSerialNumbers: false,
      electronicsRepairService: false,
      clothingVariantMatrix: false,
      hotelRooms: true,
      hotelReservations: true,
      hotelHousekeeping: true,
      hotelRoomBilling: true,
      cashRegisterShift: true,
      expenseTracking: true
    },
    createdAt: '2025-04-12T10:15:00Z',
    updatedAt: '2026-03-05T16:20:00Z'
  },
  {
    id: 'ent-electronics',
    name: 'TechNexus Computer & Mobile Solutions',
    slug: 'technexus',
    code: 'TNX-SYS',
    category: 'electronics',
    phone: '+1 (555) 345-6789',
    email: 'service@technexus.io',
    address: '302 Silicon Avenue, Tech Quarter',
    currency: 'USD',
    taxRate: 8.0,
    vatNumber: 'US-6102948-E',
    status: 'active',
    subscriptionPlanId: 'plan-pro',
    modules: {
      corePos: true,
      inventory: true,
      purchasing: true,
      customers: true,
      suppliers: true,
      accounting: true,
      barcodeSystem: true,
      restaurant: false,
      pharmacy: false,
      hardwareStore: false,
      computerMobile: true,
      clothingShoe: false,
      hotel: false
    },
    features: {
      restaurantTables: false,
      restaurantKds: false,
      restaurantRecipes: false,
      restaurantSplitBills: false,
      restaurantTakeaway: false,
      pharmacyBatchTracking: false,
      pharmacyExpiryTracking: false,
      pharmacyPrescriptions: false,
      pharmacyFefo: false,
      hardwareUnitConversions: false,
      hardwareBulkWpricing: false,
      electronicsImeiTracking: true,
      electronicsSerialNumbers: true,
      electronicsRepairService: true,
      clothingVariantMatrix: false,
      hotelRooms: false,
      hotelReservations: false,
      hotelHousekeeping: false,
      hotelRoomBilling: false,
      cashRegisterShift: true,
      expenseTracking: true
    },
    createdAt: '2025-05-20T11:00:00Z',
    updatedAt: '2026-03-08T09:40:00Z'
  },
  {
    id: 'ent-clothing',
    name: 'Vogue & Thread Boutique',
    slug: 'vogue-thread',
    code: 'VOG-APP',
    category: 'clothing',
    phone: '+1 (555) 678-9012',
    email: 'boutique@voguethread.com',
    address: '15 Fashion District, Central Arcade',
    currency: 'USD',
    taxRate: 7.5,
    vatNumber: 'US-5910293-C',
    status: 'active',
    subscriptionPlanId: 'plan-starter',
    modules: {
      corePos: true,
      inventory: true,
      purchasing: true,
      customers: true,
      suppliers: true,
      accounting: true,
      barcodeSystem: true,
      restaurant: false,
      pharmacy: false,
      hardwareStore: false,
      computerMobile: false,
      clothingShoe: true,
      hotel: false
    },
    features: {
      restaurantTables: false,
      restaurantKds: false,
      restaurantRecipes: false,
      restaurantSplitBills: false,
      restaurantTakeaway: false,
      pharmacyBatchTracking: false,
      pharmacyExpiryTracking: false,
      pharmacyPrescriptions: false,
      pharmacyFefo: false,
      hardwareUnitConversions: false,
      hardwareBulkWpricing: false,
      electronicsImeiTracking: false,
      electronicsSerialNumbers: false,
      electronicsRepairService: false,
      clothingVariantMatrix: true,
      hotelRooms: false,
      hotelReservations: false,
      hotelHousekeeping: false,
      hotelRoomBilling: false,
      cashRegisterShift: true,
      expenseTracking: true
    },
    createdAt: '2025-06-18T13:20:00Z',
    updatedAt: '2026-03-09T12:00:00Z'
  },
  {
    id: 'ent-grocery',
    name: 'Metro Fresh Supermarket',
    slug: 'metro-fresh',
    code: 'MTR-FRS',
    category: 'grocery',
    phone: '+1 (555) 123-4567',
    email: 'manager@metrofresh.com',
    address: '900 Main Boulevard, Downtown Center',
    currency: 'USD',
    taxRate: 6.0,
    vatNumber: 'US-1029384-G',
    status: 'active',
    subscriptionPlanId: 'plan-enterprise',
    modules: {
      corePos: true,
      inventory: true,
      purchasing: true,
      customers: true,
      suppliers: true,
      accounting: true,
      barcodeSystem: true,
      restaurant: false,
      pharmacy: false,
      hardwareStore: false,
      computerMobile: false,
      clothingShoe: false,
      hotel: false
    },
    features: {
      restaurantTables: false,
      restaurantKds: false,
      restaurantRecipes: false,
      restaurantSplitBills: false,
      restaurantTakeaway: false,
      pharmacyBatchTracking: true,
      pharmacyExpiryTracking: true,
      pharmacyPrescriptions: false,
      pharmacyFefo: true,
      hardwareUnitConversions: true,
      hardwareBulkWpricing: false,
      electronicsImeiTracking: false,
      electronicsSerialNumbers: false,
      electronicsRepairService: false,
      clothingVariantMatrix: false,
      hotelRooms: false,
      hotelReservations: false,
      hotelHousekeeping: false,
      hotelRoomBilling: false,
      cashRegisterShift: true,
      expenseTracking: true
    },
    createdAt: '2025-07-01T08:00:00Z',
    updatedAt: '2026-03-10T14:00:00Z'
  }
];

export const INITIAL_BRANCHES: Branch[] = [
  // Hardware branches
  { id: 'br-hdw-1', enterpriseId: 'ent-hardware', name: 'Downtown Central Store (HQ)', code: 'HDW-HQ', address: '450 Industrial Parkway', phone: '+1 (555) 234-8901', isHeadquarters: true, status: 'active' },
  { id: 'br-hdw-2', enterpriseId: 'ent-hardware', name: 'Northside Depot', code: 'HDW-NTH', address: '12 Logistics Way', phone: '+1 (555) 234-8902', isHeadquarters: false, status: 'active' },
  { id: 'br-hdw-3', enterpriseId: 'ent-hardware', name: 'West Harbor Branch', code: 'HDW-WST', address: '88 Dockside Road', phone: '+1 (555) 234-8903', isHeadquarters: false, status: 'active' },

  // Restaurant branches
  { id: 'br-rst-1', enterpriseId: 'ent-restaurant', name: 'Waterfront Promenade (HQ)', code: 'RST-MAIN', address: '88 Waterfront Promenade', phone: '+1 (555) 456-7891', isHeadquarters: true, status: 'active' },
  { id: 'br-rst-2', enterpriseId: 'ent-restaurant', name: 'Uptown Rooftop Lounge', code: 'RST-UPT', address: '45 Skyline Tower', phone: '+1 (555) 456-7892', isHeadquarters: false, status: 'active' },

  // Pharmacy branches
  { id: 'br-phm-1', enterpriseId: 'ent-pharmacy', name: 'Medical Center Main (HQ)', code: 'PHM-HQ', address: '12 Medical Center Blvd', phone: '+1 (555) 789-0121', isHeadquarters: true, status: 'active' },
  { id: 'br-phm-2', enterpriseId: 'ent-pharmacy', name: 'Suburban Care Station', code: 'PHM-SUB', address: '104 Valley Green Ave', phone: '+1 (555) 789-0122', isHeadquarters: false, status: 'active' },

  // Hotel branches
  { id: 'br-htl-1', enterpriseId: 'ent-hotel', name: 'Ocean Resort & Spa (HQ)', code: 'HTL-RES', address: '777 Oceanview Way', phone: '+1 (555) 901-2346', isHeadquarters: true, status: 'active' },

  // Electronics branches
  { id: 'br-elc-1', enterpriseId: 'ent-electronics', name: 'Tech Quarter Lab & Store (HQ)', code: 'ELC-HQ', address: '302 Silicon Avenue', phone: '+1 (555) 345-6781', isHeadquarters: true, status: 'active' },

  // Clothing branches
  { id: 'br-clt-1', enterpriseId: 'ent-clothing', name: 'Central Arcade Flagship (HQ)', code: 'CLT-FLG', address: '15 Fashion District', phone: '+1 (555) 678-9013', isHeadquarters: true, status: 'active' },

  // Grocery branches
  { id: 'br-gro-1', enterpriseId: 'ent-grocery', name: 'Downtown Supercenter (HQ)', code: 'GRO-DT', address: '900 Main Boulevard', phone: '+1 (555) 123-4568', isHeadquarters: true, status: 'active' }
];

export const INITIAL_USERS: User[] = [
  {
    id: 'usr-super-admin',
    enterpriseId: null,
    branchId: null,
    name: 'Platform Creator & Owner',
    email: 'mujaicloud1212@gmail.com',
    roleId: 'role-super-admin',
    roleTitle: 'Master Super Admin',
    avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80',
    status: 'active',
    lastLogin: '2026-03-17 08:30'
  },
  {
    id: 'usr-hdw-owner',
    enterpriseId: 'ent-hardware',
    branchId: null,
    name: 'Marcus Vance',
    email: 'marcus@abchardware.com',
    roleId: 'role-owner',
    roleTitle: 'Enterprise Owner',
    status: 'active',
    lastLogin: '2026-03-16 08:30'
  },
  {
    id: 'usr-hdw-cashier',
    enterpriseId: 'ent-hardware',
    branchId: 'br-hdw-1',
    name: 'Samantha Ray',
    email: 'samantha@abchardware.com',
    roleId: 'role-cashier',
    roleTitle: 'Head Cashier',
    status: 'active',
    lastLogin: '2026-03-16 09:00'
  },
  {
    id: 'usr-rst-manager',
    enterpriseId: 'ent-restaurant',
    branchId: 'br-rst-1',
    name: 'Chef Antonio Rossi',
    email: 'antonio@cityflavors.com',
    roleId: 'role-branch-manager',
    roleTitle: 'Restaurant Director',
    status: 'active'
  },
  {
    id: 'usr-phm-lead',
    enterpriseId: 'ent-pharmacy',
    branchId: 'br-phm-1',
    name: 'Dr. Elena Rostova',
    email: 'elena@apexpharmacy.com',
    roleId: 'role-branch-manager',
    roleTitle: 'Chief Pharmacist',
    status: 'active'
  },
  {
    id: 'usr-htl-manager',
    enterpriseId: 'ent-hotel',
    branchId: 'br-htl-1',
    name: 'Julian Sterling',
    email: 'julian@grandhorizon.com',
    roleId: 'role-branch-manager',
    roleTitle: 'General Manager',
    status: 'active'
  },
  {
    id: 'usr-elc-tech',
    enterpriseId: 'ent-electronics',
    branchId: 'br-elc-1',
    name: 'Devin Chen',
    email: 'devin@technexus.io',
    roleId: 'role-branch-manager',
    roleTitle: 'Lead Hardware Engineer',
    status: 'active'
  }
];

export const INITIAL_PRODUCTS: Product[] = [
  // ABC Hardware Products
  {
    id: 'prod-hdw-1',
    enterpriseId: 'ent-hardware',
    name: 'DeWalt 20V Max Cordless Hammer Drill Kit',
    sku: 'DWT-DCD996B',
    barcode: '2001089201941',
    barcodeType: 'CODE128',
    categoryId: 'cat-tools',
    categoryName: 'Power Tools',
    brand: 'DeWalt',
    costPrice: 120.00,
    sellingPrice: 189.99,
    wholesalePrice: 160.00,
    stock: 45,
    minStock: 10,
    maxStock: 100,
    unit: 'pcs',
    description: 'Heavy-duty 3-speed brushless high-performance hammerdrill with carrying case and charger.',
    status: 'active',
    variants: [],
    dimensions: { length: 25, width: 10, thickness: 20, unit: 'cm' },
    createdAt: '2025-01-15T09:00:00Z',
    updatedAt: '2026-02-10T11:00:00Z'
  },
  {
    id: 'prod-hdw-2',
    enterpriseId: 'ent-hardware',
    name: 'Portland High-Grade Cement 50kg',
    sku: 'CEM-PRT-50K',
    barcode: '2004928172048',
    barcodeType: 'CODE128',
    categoryId: 'cat-building',
    categoryName: 'Building Materials',
    brand: 'Holcim',
    costPrice: 7.20,
    sellingPrice: 11.50,
    wholesalePrice: 9.80,
    stock: 350,
    minStock: 50,
    maxStock: 500,
    unit: 'bag',
    description: 'Type 1 Portland hydraulic cement for general concrete construction and masonry.',
    status: 'active',
    variants: [],
    createdAt: '2025-01-15T09:30:00Z',
    updatedAt: '2026-02-15T14:20:00Z'
  },
  {
    id: 'prod-hdw-3',
    enterpriseId: 'ent-hardware',
    name: 'Deformed Steel Rebar 12mm x 6m',
    sku: 'STL-RBR-12MM',
    barcode: '2008492018471',
    barcodeType: 'CODE128',
    categoryId: 'cat-building',
    categoryName: 'Building Materials',
    brand: 'Vulcan Steel',
    costPrice: 8.50,
    sellingPrice: 13.90,
    wholesalePrice: 11.20,
    stock: 820,
    minStock: 100,
    maxStock: 1500,
    unit: 'meter',
    description: 'High tensile carbon steel reinforcing rebar for reinforced concrete structures.',
    status: 'active',
    variants: [],
    dimensions: { length: 6, unit: 'meter' },
    createdAt: '2025-01-20T10:00:00Z',
    updatedAt: '2026-02-18T16:00:00Z'
  },
  {
    id: 'prod-hdw-4',
    enterpriseId: 'ent-hardware',
    name: 'Heavy Duty Brass Ball Valve 1/2 Inch',
    sku: 'PLM-BVL-050',
    barcode: '2003820194812',
    barcodeType: 'CODE128',
    categoryId: 'cat-plumbing',
    categoryName: 'Plumbing & Pipes',
    brand: 'Watts',
    costPrice: 4.80,
    sellingPrice: 8.95,
    wholesalePrice: 7.20,
    stock: 140,
    minStock: 25,
    maxStock: 300,
    unit: 'pcs',
    description: 'Lead-free full port brass ball valve with vinyl grip lever handle.',
    status: 'active',
    variants: [],
    createdAt: '2025-01-22T11:00:00Z',
    updatedAt: '2026-02-20T12:00:00Z'
  },

  // City Flavors Bistro Products
  {
    id: 'prod-rst-1',
    enterpriseId: 'ent-restaurant',
    name: 'Prime Angus Ribeye Steak 350g',
    sku: 'RST-RBE-350',
    barcode: '2006192048193',
    barcodeType: 'CODE128',
    categoryId: 'cat-mains',
    categoryName: 'Grill & Steaks',
    costPrice: 14.50,
    sellingPrice: 38.00,
    stock: 60,
    minStock: 15,
    maxStock: 100,
    unit: 'plate',
    description: 'USDA Prime dry-aged 28-day ribeye with roasted garlic herb butter and rosemary fries.',
    status: 'active',
    variants: [],
    createdAt: '2025-02-15T10:00:00Z',
    updatedAt: '2026-03-01T12:00:00Z'
  },
  {
    id: 'prod-rst-2',
    enterpriseId: 'ent-restaurant',
    name: 'Handcrafted Truffle Fettuccine',
    sku: 'RST-PST-TRF',
    barcode: '2007820194815',
    barcodeType: 'CODE128',
    categoryId: 'cat-pasta',
    categoryName: 'Handmade Pasta',
    costPrice: 5.20,
    sellingPrice: 24.50,
    stock: 85,
    minStock: 20,
    maxStock: 150,
    unit: 'plate',
    description: 'Fresh egg fettuccine tossed in black summer truffle cream with Parmigiano Reggiano.',
    status: 'active',
    variants: [],
    createdAt: '2025-02-15T10:30:00Z',
    updatedAt: '2026-03-01T12:15:00Z'
  },
  {
    id: 'prod-rst-3',
    enterpriseId: 'ent-restaurant',
    name: 'Artisan Burrata & Heirloom Tomato',
    sku: 'RST-APP-BRT',
    barcode: '2009820194821',
    barcodeType: 'CODE128',
    categoryId: 'cat-starters',
    categoryName: 'Starters & Salads',
    costPrice: 4.10,
    sellingPrice: 16.00,
    stock: 40,
    minStock: 10,
    maxStock: 80,
    unit: 'plate',
    description: 'Creamy Puglia burrata, organic heirloom tomatoes, basil pesto drizzle and sourdough crostini.',
    status: 'active',
    variants: [],
    createdAt: '2025-02-16T11:00:00Z',
    updatedAt: '2026-03-01T12:30:00Z'
  },

  // Apex Care Pharmacy Products
  {
    id: 'prod-phm-1',
    enterpriseId: 'ent-pharmacy',
    name: 'Amoxicillin Trihydrate 500mg Capsules',
    sku: 'MED-AMX-500',
    barcode: '2003849102941',
    barcodeType: 'CODE128',
    categoryId: 'cat-antibiotics',
    categoryName: 'Antibiotics & Anti-infectives',
    brand: 'Sandoz Pharma',
    costPrice: 6.20,
    sellingPrice: 14.50,
    stock: 120,
    minStock: 30,
    maxStock: 300,
    unit: 'box',
    genericName: 'Amoxicillin',
    dosageForm: 'Capsule (500mg, 30s)',
    batchNumber: 'AMX-2025-09A',
    expiryDate: '2027-08-30',
    isPrescriptionRequired: true,
    description: 'Broad-spectrum penicillin antibiotic for bacterial infections.',
    status: 'active',
    variants: [],
    createdAt: '2025-03-02T08:00:00Z',
    updatedAt: '2026-03-05T09:00:00Z'
  },
  {
    id: 'prod-phm-2',
    enterpriseId: 'ent-pharmacy',
    name: 'Paracetamol Extra Rapid Action 500mg',
    sku: 'MED-PCM-500',
    barcode: '2007482019481',
    barcodeType: 'CODE128',
    categoryId: 'cat-analgesics',
    categoryName: 'Pain & Fever Relief',
    brand: 'GSK Consumer',
    costPrice: 1.80,
    sellingPrice: 4.90,
    stock: 350,
    minStock: 50,
    maxStock: 600,
    unit: 'box',
    genericName: 'Acetaminophen / Paracetamol',
    dosageForm: 'Tablet (500mg, 24s)',
    batchNumber: 'PCM-2026-01B',
    expiryDate: '2028-02-15',
    isPrescriptionRequired: false,
    description: 'Fast-absorbing analgesic and antipyretic for mild to moderate pain relief.',
    status: 'active',
    variants: [],
    createdAt: '2025-03-02T08:30:00Z',
    updatedAt: '2026-03-05T09:30:00Z'
  },
  {
    id: 'prod-phm-3',
    enterpriseId: 'ent-pharmacy',
    name: 'Atorvastatin Calcium 20mg Lipitor Equivalent',
    sku: 'MED-ATV-020',
    barcode: '2001928374612',
    barcodeType: 'CODE128',
    categoryId: 'cat-cardio',
    categoryName: 'Cardiovascular Care',
    brand: 'Pfizer',
    costPrice: 9.40,
    sellingPrice: 22.00,
    stock: 90,
    minStock: 25,
    maxStock: 200,
    unit: 'box',
    genericName: 'Atorvastatin',
    dosageForm: 'Film-coated tablet (20mg, 30s)',
    batchNumber: 'ATV-2025-11C',
    expiryDate: '2026-06-25', // Near expiry to trigger alert!
    isPrescriptionRequired: true,
    description: 'HMG-CoA reductase inhibitor for lipid and cholesterol management.',
    status: 'active',
    variants: [],
    createdAt: '2025-03-02T09:00:00Z',
    updatedAt: '2026-03-05T10:00:00Z'
  },

  // TechNexus Electronics Products
  {
    id: 'prod-elc-1',
    enterpriseId: 'ent-electronics',
    name: 'Apple iPhone 15 Pro 256GB Natural Titanium',
    sku: 'APL-IPH15P-256',
    barcode: '2004810294812',
    barcodeType: 'CODE128',
    categoryId: 'cat-smartphones',
    categoryName: 'Smartphones & Devices',
    brand: 'Apple',
    costPrice: 880.00,
    sellingPrice: 1099.00,
    stock: 14,
    minStock: 5,
    maxStock: 40,
    unit: 'pcs',
    imeiNumber: '358941092847102',
    serialNumber: 'C7G892K1094',
    warrantyMonths: 12,
    description: 'A17 Pro chip, titanium design, 48MP main camera system, Super Retina XDR display.',
    status: 'active',
    variants: [],
    createdAt: '2025-05-22T10:00:00Z',
    updatedAt: '2026-03-08T11:00:00Z'
  },
  {
    id: 'prod-elc-2',
    enterpriseId: 'ent-electronics',
    name: 'Kingston KC3000 PCIe 4.0 NVMe M.2 SSD 1TB',
    sku: 'KNG-KC3000-1T',
    barcode: '2008492014819',
    barcodeType: 'CODE128',
    categoryId: 'cat-components',
    categoryName: 'Computer Components',
    brand: 'Kingston',
    costPrice: 65.00,
    sellingPrice: 94.99,
    wholesalePrice: 82.00,
    stock: 38,
    minStock: 10,
    maxStock: 80,
    unit: 'pcs',
    serialNumber: 'SN-948102948A',
    warrantyMonths: 60,
    description: 'Read speeds up to 7,000MB/s, Phison E18 controller, graphene aluminum heat spreader.',
    status: 'active',
    variants: [],
    createdAt: '2025-05-23T11:00:00Z',
    updatedAt: '2026-03-08T11:30:00Z'
  },

  // Vogue & Thread Clothing
  {
    id: 'prod-clt-1',
    enterpriseId: 'ent-clothing',
    name: 'Artisan Oxford Cotton Tailored Shirt',
    sku: 'VOG-OXF-SHT',
    barcode: '2001928401924',
    barcodeType: 'CODE128',
    categoryId: 'cat-menswear',
    categoryName: 'Men Tailoring',
    brand: 'Vogue & Thread',
    costPrice: 22.00,
    sellingPrice: 59.00,
    stock: 64,
    minStock: 15,
    maxStock: 120,
    unit: 'pcs',
    description: '100% Egyptian combed cotton with mother-of-pearl buttons and tailored spread collar.',
    status: 'active',
    variants: [
      { id: 'var-1', productId: 'prod-clt-1', name: 'White / Small', sku: 'VOG-OXF-WHT-S', barcode: '2001928401925', costPrice: 22, sellingPrice: 59, stock: 12, attributes: { Size: 'S', Color: 'White' } },
      { id: 'var-2', productId: 'prod-clt-1', name: 'White / Medium', sku: 'VOG-OXF-WHT-M', barcode: '2001928401926', costPrice: 22, sellingPrice: 59, stock: 20, attributes: { Size: 'M', Color: 'White' } },
      { id: 'var-3', productId: 'prod-clt-1', name: 'White / Large', sku: 'VOG-OXF-WHT-L', barcode: '2001928401927', costPrice: 22, sellingPrice: 59, stock: 18, attributes: { Size: 'L', Color: 'White' } },
      { id: 'var-4', productId: 'prod-clt-1', name: 'Navy / Medium', sku: 'VOG-OXF-NVY-M', barcode: '2001928401928', costPrice: 22, sellingPrice: 59, stock: 14, attributes: { Size: 'M', Color: 'Navy' } }
    ],
    createdAt: '2025-06-20T10:00:00Z',
    updatedAt: '2026-03-09T14:00:00Z'
  },

  // Metro Fresh Grocery
  {
    id: 'prod-gro-1',
    enterpriseId: 'ent-grocery',
    name: 'Organic Whole Pasture Milk 1 Gallon',
    sku: 'GRO-MLK-1GL',
    barcode: '2004819204812',
    barcodeType: 'CODE128',
    categoryId: 'cat-dairy',
    categoryName: 'Dairy & Chilled',
    brand: 'Valley Organic',
    costPrice: 2.80,
    sellingPrice: 4.89,
    stock: 95,
    minStock: 25,
    maxStock: 200,
    unit: 'bottle',
    batchNumber: 'MLK-0316',
    expiryDate: '2026-03-24',
    description: 'Grade A pasteurized whole milk from grass-fed cows.',
    status: 'active',
    variants: [],
    createdAt: '2025-07-02T08:00:00Z',
    updatedAt: '2026-03-10T15:00:00Z'
  },
  {
    id: 'prod-gro-2',
    enterpriseId: 'ent-grocery',
    name: 'Barilla Collezione Tagliatelle 500g',
    sku: 'GRO-BAR-TAG',
    barcode: '2009281740192',
    barcodeType: 'CODE128',
    categoryId: 'cat-pantry',
    categoryName: 'Pantry & Grains',
    brand: 'Barilla',
    costPrice: 1.40,
    sellingPrice: 3.29,
    stock: 210,
    minStock: 40,
    maxStock: 400,
    unit: 'box',
    description: 'Traditional bronze-cut egg pasta nests crafted with premium semolina.',
    status: 'active',
    variants: [],
    createdAt: '2025-07-02T08:30:00Z',
    updatedAt: '2026-03-10T15:30:00Z'
  }
];

export const INITIAL_CUSTOMERS: Customer[] = [
  {
    id: 'cust-1',
    enterpriseId: 'ent-hardware',
    name: 'Apex Construction Co.',
    phone: '+1 (555) 948-2019',
    email: 'accounts@apexconstruction.com',
    address: '800 Builder Ave, Suite 4B',
    loyaltyPoints: 1450,
    outstandingBalance: 1240.00,
    creditLimit: 5000.00,
    totalSpent: 18450.00,
    notes: 'Preferred commercial contractor with net-30 terms',
    createdAt: '2025-02-01T10:00:00Z'
  },
  {
    id: 'cust-2',
    enterpriseId: 'ent-hardware',
    name: 'Robert Hastings',
    phone: '+1 (555) 481-9204',
    email: 'robert.h@gmail.com',
    address: '42 Pine Crest Road',
    loyaltyPoints: 320,
    outstandingBalance: 0,
    creditLimit: 500.00,
    totalSpent: 1290.50,
    notes: 'DIY home renovator',
    createdAt: '2025-03-10T14:00:00Z'
  },
  {
    id: 'cust-3',
    enterpriseId: 'ent-restaurant',
    name: 'Sophia Montgomery',
    phone: '+1 (555) 749-1029',
    email: 'sophia.m@luxuryestate.com',
    address: '12 Harbor View Court',
    loyaltyPoints: 890,
    outstandingBalance: 0,
    creditLimit: 1000.00,
    totalSpent: 3450.00,
    notes: 'VIP guest, prefers Window Booth Table 4',
    createdAt: '2025-02-20T19:00:00Z'
  }
];

export const INITIAL_SUPPLIERS: Supplier[] = [
  {
    id: 'sup-1',
    enterpriseId: 'ent-hardware',
    companyName: 'DeWalt Industrial Tool Supply Co.',
    contactPerson: 'David Miller',
    phone: '+1 (555) 800-4392',
    email: 'orders@dewalt-industrial.com',
    address: '700 Power Tool Way, Maryland',
    taxNumber: 'US-84920491',
    paymentTerms: 'Net 30',
    outstandingBalance: 4500.00,
    createdAt: '2025-01-10T09:00:00Z'
  },
  {
    id: 'sup-2',
    enterpriseId: 'ent-hardware',
    companyName: 'Vulcan Steel & Metalworks Ltd.',
    contactPerson: 'Sarah Jenkins',
    phone: '+1 (555) 820-9481',
    email: 'distribution@vulcansteel.com',
    address: '1200 Heavy Foundry Blvd, Ohio',
    taxNumber: 'US-92019481',
    paymentTerms: 'Net 15',
    outstandingBalance: 11200.00,
    createdAt: '2025-01-12T11:00:00Z'
  }
];

export const INITIAL_TABLES: RestaurantTable[] = [
  { id: 'tbl-1', enterpriseId: 'ent-restaurant', branchId: 'br-rst-1', number: 'T-01', capacity: 2, zone: 'Main Dining', status: 'available' },
  { id: 'tbl-2', enterpriseId: 'ent-restaurant', branchId: 'br-rst-1', number: 'T-02', capacity: 4, zone: 'Main Dining', status: 'occupied', activeOrderTotal: 98.50, activeOrderTime: '35m ago' },
  { id: 'tbl-3', enterpriseId: 'ent-restaurant', branchId: 'br-rst-1', number: 'T-03', capacity: 4, zone: 'Main Dining', status: 'billing', activeOrderTotal: 142.00, activeOrderTime: '55m ago' },
  { id: 'tbl-4', enterpriseId: 'ent-restaurant', branchId: 'br-rst-1', number: 'T-04', capacity: 6, zone: 'VIP Lounge', status: 'reserved' },
  { id: 'tbl-5', enterpriseId: 'ent-restaurant', branchId: 'br-rst-1', number: 'P-01', capacity: 4, zone: 'Patio', status: 'available' },
  { id: 'tbl-6', enterpriseId: 'ent-restaurant', branchId: 'br-rst-1', number: 'P-02', capacity: 2, zone: 'Patio', status: 'occupied', activeOrderTotal: 62.50, activeOrderTime: '18m ago' },
  { id: 'tbl-7', enterpriseId: 'ent-restaurant', branchId: 'br-rst-1', number: 'BAR-1', capacity: 2, zone: 'Bar Area', status: 'available' },
  { id: 'tbl-8', enterpriseId: 'ent-restaurant', branchId: 'br-rst-1', number: 'BAR-2', capacity: 2, zone: 'Bar Area', status: 'available' }
];

export const INITIAL_KITCHEN_ORDERS: KitchenOrder[] = [
  {
    id: 'kds-1',
    enterpriseId: 'ent-restaurant',
    branchId: 'br-rst-1',
    orderNumber: 'KDS-#408',
    tableNumber: 'T-02',
    diningType: 'dine_in',
    items: [
      { name: 'Prime Angus Ribeye Steak 350g', qty: 2, notes: 'Medium-rare, extra garlic butter', isDone: false },
      { name: 'Handcrafted Truffle Fettuccine', qty: 1, notes: 'No parsley', isDone: true }
    ],
    status: 'preparing',
    createdAt: '12m ago'
  },
  {
    id: 'kds-2',
    enterpriseId: 'ent-restaurant',
    branchId: 'br-rst-1',
    orderNumber: 'KDS-#409',
    tableNumber: 'P-02',
    diningType: 'dine_in',
    items: [
      { name: 'Artisan Burrata & Heirloom Tomato', qty: 1, notes: 'Gluten-free crostini', isDone: false }
    ],
    status: 'pending',
    createdAt: '4m ago'
  }
];

export const INITIAL_REPAIR_TICKETS: RepairTicket[] = [
  {
    id: 'rep-1',
    enterpriseId: 'ent-electronics',
    branchId: 'br-elc-1',
    ticketNumber: 'REP-9081',
    customerName: 'Marcus Aurelius',
    customerPhone: '+1 (555) 918-2049',
    deviceType: 'Laptop',
    brandModel: 'Dell XPS 15 9520',
    serialOrImei: 'SN-49102948-DL',
    issueDescription: 'Battery thermal throttling and cooling fan bearing noise under load.',
    technicianName: 'Devin Chen',
    status: 'in_repair',
    laborCharge: 85.00,
    partsCharge: 65.00,
    totalEstimate: 150.00,
    receivedDate: '2026-03-14'
  },
  {
    id: 'rep-2',
    enterpriseId: 'ent-electronics',
    branchId: 'br-elc-1',
    ticketNumber: 'REP-9082',
    customerName: 'Jessica Bloom',
    customerPhone: '+1 (555) 710-2948',
    deviceType: 'Smartphone',
    brandModel: 'iPhone 14 Pro Max',
    serialOrImei: 'IMEI-359102948102948',
    issueDescription: 'Cracked front OLED glass panel after drop, touch digitizer unresponsive on top right.',
    technicianName: 'Devin Chen',
    status: 'waiting_parts',
    laborCharge: 60.00,
    partsCharge: 195.00,
    totalEstimate: 255.00,
    receivedDate: '2026-03-15'
  }
];

export const INITIAL_HOTEL_ROOMS: HotelRoom[] = [
  { id: 'room-101', enterpriseId: 'ent-hotel', roomNumber: '101', type: 'Single Standard', capacity: 2, pricePerNight: 120, status: 'available' },
  { id: 'room-102', enterpriseId: 'ent-hotel', roomNumber: '102', type: 'Single Standard', capacity: 2, pricePerNight: 120, status: 'cleaning' },
  { id: 'room-201', enterpriseId: 'ent-hotel', roomNumber: '201', type: 'Deluxe Ocean View', capacity: 3, pricePerNight: 240, status: 'occupied', currentGuestName: 'Victoria Sterling', checkInDate: '2026-03-14', checkOutDate: '2026-03-18', folioBalance: 580.00 },
  { id: 'room-202', enterpriseId: 'ent-hotel', roomNumber: '202', type: 'Deluxe Ocean View', capacity: 3, pricePerNight: 240, status: 'available' },
  { id: 'room-301', enterpriseId: 'ent-hotel', roomNumber: '301', type: 'Executive Suite', capacity: 4, pricePerNight: 450, status: 'occupied', currentGuestName: 'Lord Harrison', checkInDate: '2026-03-15', checkOutDate: '2026-03-20', folioBalance: 1240.00 },
  { id: 'room-401', enterpriseId: 'ent-hotel', roomNumber: '401', type: 'Family Villa', capacity: 6, pricePerNight: 650, status: 'available' }
];

export const INITIAL_SALES: Sale[] = [
  {
    id: 'sale-1001',
    enterpriseId: 'ent-hardware',
    branchId: 'br-hdw-1',
    branchName: 'Downtown Central Store (HQ)',
    invoiceNumber: 'INV-HDW-2026-001',
    customerId: 'cust-1',
    customerName: 'Apex Construction Co.',
    customerPhone: '+1 (555) 948-2019',
    items: [
      {
        productId: 'prod-hdw-1',
        name: 'DeWalt 20V Max Cordless Hammer Drill Kit',
        sku: 'DWT-DCD996B',
        barcode: '2001089201941',
        price: 189.99,
        quantity: 2,
        unit: 'pcs',
        discount: 0,
        discountType: 'percent',
        taxRate: 8.5
      },
      {
        productId: 'prod-hdw-2',
        name: 'Portland High-Grade Cement 50kg',
        sku: 'CEM-PRT-50K',
        barcode: '2004928172048',
        price: 11.50,
        quantity: 10,
        unit: 'bag',
        discount: 5,
        discountType: 'percent',
        taxRate: 8.5
      }
    ],
    subtotal: 489.23,
    discountAmount: 5.75,
    taxAmount: 41.09,
    serviceCharge: 0,
    total: 524.57,
    paymentMethod: 'card',
    amountPaid: 524.57,
    changeDue: 0,
    status: 'completed',
    cashierId: 'usr-hdw-cashier',
    cashierName: 'Samantha Ray',
    createdAt: '2026-03-15T14:35:00Z'
  },
  {
    id: 'sale-1002',
    enterpriseId: 'ent-restaurant',
    branchId: 'br-rst-1',
    branchName: 'Waterfront Promenade (HQ)',
    invoiceNumber: 'INV-RST-2026-089',
    items: [
      {
        productId: 'prod-rst-1',
        name: 'Prime Angus Ribeye Steak 350g',
        sku: 'RST-RBE-350',
        barcode: '2006192048193',
        price: 38.00,
        quantity: 2,
        unit: 'plate',
        discount: 0,
        discountType: 'percent',
        taxRate: 10
      },
      {
        productId: 'prod-rst-3',
        name: 'Artisan Burrata & Heirloom Tomato',
        sku: 'RST-APP-BRT',
        barcode: '2009820194821',
        price: 16.00,
        quantity: 1,
        unit: 'plate',
        discount: 0,
        discountType: 'percent',
        taxRate: 10
      }
    ],
    subtotal: 92.00,
    discountAmount: 0,
    taxAmount: 9.20,
    serviceCharge: 9.20,
    total: 110.40,
    paymentMethod: 'cash',
    amountPaid: 120.00,
    changeDue: 9.60,
    status: 'completed',
    cashierId: 'usr-rst-manager',
    cashierName: 'Chef Antonio Rossi',
    tableNumber: 'T-03',
    diningType: 'dine_in',
    createdAt: '2026-03-15T20:10:00Z'
  }
];

export const INITIAL_AUDIT_LOGS: AuditLog[] = [
  {
    id: 'aud-1',
    enterpriseId: 'ent-hardware',
    branchId: 'br-hdw-1',
    userId: 'usr-hdw-owner',
    userName: 'Marcus Vance',
    action: 'PRODUCT_CREATED',
    entity: 'Product',
    recordId: 'prod-hdw-1',
    details: 'Created product DeWalt 20V Max Cordless Hammer Drill Kit with SKU DWT-DCD996B',
    timestamp: '2026-03-14 10:20:00'
  },
  {
    id: 'aud-2',
    enterpriseId: 'ent-hardware',
    branchId: 'br-hdw-1',
    userId: 'usr-hdw-cashier',
    userName: 'Samantha Ray',
    action: 'SALE_COMPLETED',
    entity: 'Sale',
    recordId: 'sale-1001',
    details: 'Completed card transaction invoice #INV-HDW-2026-001 for Apex Construction Co ($524.57)',
    timestamp: '2026-03-15 14:35:00'
  },
  {
    id: 'aud-3',
    enterpriseId: 'ent-hardware',
    branchId: 'br-hdw-1',
    userId: 'usr-super-admin',
    userName: 'Alexander Cross',
    action: 'FEATURE_TOGGLED',
    entity: 'EnterpriseModule',
    recordId: 'ent-hardware',
    details: 'Updated feature configuration for ABC Hardware: Core POS=ON, Hardware=ON, Restaurant=OFF',
    timestamp: '2026-03-16 09:12:00'
  }
];
